import Head from "next/head";
import Image from "next/image";
import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container-fluid">
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          Get started by editing <code>pages/index.tsx</code>
        </p>
        <div className="grid">
          <article>
            <header>
              <h2 style={{ marginBottom: 0 }}>Documentation</h2>
            </header>
            <p>Find in-depth information about Next.js features and API.</p>
            <a
              href="https://nextjs.org/docs"
              role="button"
              className="contrast outline"
            >
              Read &#8594;
            </a>
          </article>

          <article>
            <header>
              <h2 style={{ marginBottom: 0 }}>Learn</h2>
            </header>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
            <a
              href="https://nextjs.org/learn"
              role="button"
              className="contrast outline"
            >
              Go &#8594;
            </a>
          </article>
        </div>
        <div className="grid">
          <article>
            <header>
              <h2 style={{ marginBottom: 0 }}>Examples</h2>
            </header>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
            <a
              href="https://github.com/vercel/next.js/tree/master/examples"
              role="button"
              className="contrast outline"
            >
              View &#8594;
            </a>
          </article>

          <article>
            <header>
              <h2 style={{ marginBottom: 0 }}>Deploy </h2>
            </header>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              role="button"
              className="contrast outline"
            >
              View &#8594;
            </a>
          </article>
        </div>
      </main>

      <footer
        style={{
          display: "flex",
          flexDirection: "row",
          alignItems: "center",
          justifyContent: "center",
          paddingBottom: "2rem",
        }}
      >
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
